#\DeclareLyXModule{Trustifier Document}
#DescriptionBegin
#Provides Trustifier Logos and Fonts and other nice 
#standard things.
#DescriptionEnd

Format 60

AddToPreamble
EndPreamble

Input trustifier-base-fonts.inc
Input trustifier-base-logos.inc
Input trustifier-base-styles.inc
Input trustifier-base-page-layout.inc


InsetLayout "Flex:Trustifier Logo"
	ContentAsLabel	true
	LatexType	Command
	LatexName	TrustifierLogo
	LabelString     "Trustifier"
	LyxType 	custom
	Decoration	Classic
	Font
		Color   blue
		Family 	Sans
		Shape	SmallCaps
	EndFont
End

InsetLayout "Flex:Product Logo"
	
	CopyStyle	"Flex:Trustifier Logo"

	LatexType	Command
	LatexName	TrustifierProduct
	LabelString     "Product:"

End


# vim:filetype=lyx-layout
