#% Do not delete the lines below LyX depends on them
#\DeclareLyXModule{Trustifier Document}
#DescriptionBegin
#Provides Trustifier Logos and Fonts and other nice 
#standard things.
#DescriptionEnd
#EndLyXDeclaration

Format 60


NoStyle Verse
NoStyle Poemtitle
NoStyle Poemtitle*

Input trustifier-base-fonts.inc
Input trustifier-base-logos.inc

AddToPreamble
	\setromanfont[
		Ligatures=TeX,
		Scale=MatchLowercase
	]{Palatino}
	\setsansfont[
		Ligatures=TeX,
		UprightFont={* Light},
		BoldFont={* Medium}
	]{Roboto}
	\setmonofont{FreeMono}
	% -- define default family as sans
	\renewcommand{\familydefault}{\sfdefault}
EndPreamble

Input trustifier-base-styles.inc
Input trustifier-base-page-layout.inc

InsetLayout "Flex:Trustifier Logo"
	ContentAsLabel	true
	LatexType	Command
	LatexName	TrustifierLogo
	LabelString     "Trustifier"
	LyxType 	custom
	Decoration	Classic
	Font
		Color   blue
		Family 	Sans
		Shape	SmallCaps
	EndFont
End

InsetLayout "Flex:Product Logo"

	CopyStyle	"Flex:Trustifier Logo"

	LatexType	Command
	LatexName	TrustifierProduct
	LabelString     "Product:"

End
